### PR TITLE
fix: line endings are set based on file

### LINKED ISSUE #161: Unusable as 'pre-commit' hook, since it will always fail.
Hi, I would like to point out a potential problem with `pre-commit` usage of `doctoc`. Since `doctoc` always updates files, which contain any headings, *regardless of changes* since the last run, it will *always* modify files and cause the `pre-commit` hook to fail and revert the changes. 

This makes, in my opinion, `doctoc` unusable as a pre-commit hook as is, since it will cause every commit which would update a markdown file fail. The only option you are left with (and please correct me if I'm wrong) is to either skip `pre-commit` on that commit or remove `doctoc` from your `pre-commit-config.yaml`.

### Suggestion

Since `pre-commit` aims more towards hooks which only check but, do not modify any files (such as linters, etc. ) the only way I see `doctoc` being used as a hook, would be if it only updated the files which had their structure changed since the last `doctoc` run or it had a mode in which it would simply run this check and fail, if some files needed updates. (Since both of them require this check to happen, it makes sense to implement it either way)

The way `doctoc` is working right now (and again, this is just *my* opinion and I'm open to being corrected) is not compatible with the direction `pre-commit` is heading. So in my humble opinion, the `pre-commit` integration in the current state is deprecated and it should either be addressed, or marked as suc. Again, I'm open for discussion.

### PR DESCRIPTION
**Pull request by thompson-tomo**
Closes: #161 
Closes: #216

Tool now detects what line endings have been used in the content and uses that in the generated toc to strive for consistency.

Blocked by: #337 & #338

### CODE REVIEW

File: lib/transform.js [hunk 1]
```diff
@@ -117,13 +117,30 @@ function determineTitle(title, notitle, lines, info) {
...
+  const lf = (content.match(/\n/g) || []).length - crlf;
+
+  // Count all \r, then subtract CRLF occurrences
+  const cr = (content.match(/\r/g) || []).length - crlf;
+
+  if (crlf > lf && crlf > cr) return '\r\n';
+  if (lf > crlf && lf > cr)   return '\n';
+  if (cr > crlf && cr > lf)   return '\r';
+
+  return '\n';
```
Comment (thompson-tomo) [inline lib/transform.js]: Should this default be user definable? Cc @AndrewSouthpaw

File: lib/transform.js [hunk 2]
```diff
@@ -117,13 +117,30 @@ function determineTitle(title, notitle, lines, info) {
...
+
+  // Count all \n, then subtract CRLF occurrences
+  const lf = (content.match(/\n/g) || []).length - crlf;
+
+  // Count all \r, then subtract CRLF occurrences
+  const cr = (content.match(/\r/g) || []).length - crlf;
+
+  if (crlf > lf && crlf > cr) return '\r\n';
+  if (lf > crlf && lf > cr)   return '\n';
+  if (cr > crlf && cr > lf)   return '\r';
```
Comment (thompson-tomo) [inline lib/transform.js]: I am not sure about how we should handle files with mixed endings. Perhaps we should do.

```suggestion
  if (lf + cr === 0 && crlf > 0)   return '\r\n';
  if (crlf + cr === 0 && lf > 0)   return '\n';
  if (crlf + lf === 0 && cr > 0)   return '\r';
```

Thoughts @AndrewSouthpaw

Comment (AndrewSouthpaw) [reply lib/transform.js]: Hmmm this could be a major change, as I mentioned [here](https://github.com/thlorenz/doctoc/pull/216#pullrequestreview-860417728).

IMO it'd make sense for this to be behind a flag for v2, and change the default to automatically detect for v3.

For files with mixed line endings, I'm leaning towards throwing, because there's not really a reasonable thing to do. Whatever we choose, it could be the wrong behavior for the user, and quite subtle. We can give a flag for them to choose the override (below).

Printing a warning would be another option, but I'm generally a fan of failing fast, especially given that mixed line endings is probably an indication that something is weird and wrong about their file, and it'd be helpful for them to know about it.

Thoughts?

File: lib/transform.js [hunk 3]
```diff
@@ -117,13 +117,30 @@ function determineTitle(title, notitle, lines, info) {
...
+  const crlf = (content.match(/\r\n/g) || []).length;
+
+  // Count all \n, then subtract CRLF occurrences
+  const lf = (content.match(/\n/g) || []).length - crlf;
+
+  // Count all \r, then subtract CRLF occurrences
+  const cr = (content.match(/\r/g) || []).length - crlf;
+
+  if (crlf > lf && crlf > cr) return '\r\n';
+  if (lf > crlf && lf > cr)   return '\n';
```
Comment (AndrewSouthpaw) [inline lib/transform.js]: In the spirit of optimization for large files, we could avoid 3 scans of regex matches like this:

```ts
  function detectLineEnding(content) {
    var crlf = 0, lf = 0, cr = 0;
    for (var i = 0; i < content.length; i++) {
      if (content[i] === '\r') {
        if (content[i + 1] === '\n') { crlf++; i++; }
        else { cr++; }
      } else if (content[i] === '\n') { lf++; }
    }
```

As much as I hate for loops 😅

File: lib/transform.js (hunk 1 above)
Comment (AndrewSouthpaw) [reply lib/transform.js]: That would ease some of what I mention above. Something like --line-ending-default or something, which we can fall back to (and not throw) in cases of mixed line endings.

File: lib/transform.js [hunk 4]
```diff
@@ -174,31 +188,30 @@ exports = module.exports = function transform(content, mode, maxHeaderLevel, min
...
-      end = options.toc.footer.content + '\n' + end;
-    }
-    
+        }));
+
+    tocL.push('');
+    if (options?.toc?.footer?.content) { tocL.push(options.toc.footer.content); }
+
+    toc = tocL.join('\n');
     wrappedToc = start + '\n' + toc + '\n' + end;
```
Comment (AndrewSouthpaw) [inline lib/transform.js]: I'm guessing this isn't yet done b/c it's still in draft form, but lines like these need to be updated, otherwise `\r\n` files still get marked as modified:

```js
test('up-to-date toc in \\r\\n file is not marked as transformed', function (t) {
  var mdCrlf = [
      '<!-- START doctoc generated TOC please keep comment here to allow auto update -->'
    , '<!-- DON\'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->'
    , '**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*'
    , ''
    , '- [Header](#header)'
    , ''
    , '<!-- END doctoc generated TOC please keep comment here to allow auto update -->'
    , ''
    , '## Header'
    , 'some content'
    , ''
    ].join('\r\n')

  var resCrlf = transform(mdCrlf)
  t.same(resCrlf.transformed, false, '\\r\\n version should also be up to date')
  t.end()
})
```

Comment (thompson-tomo) [reply lib/transform.js]: Yeap this PR will need a rebase once the prior is merged, verification all instances are caught & tests added.

File: lib/transform.js (hunk 2 above)
Comment (thompson-tomo) [reply lib/transform.js]: I agree #216 would be a major change especially as it uses the system default rather than detecting and it also re-writes the entire doc.

I think it would be ok if document is consistent use what is detected, otherwise use configured which has a default of '\n'.

This would mean:

- \n docs already with upto date toc would always use \n
- \r\n docs already with upto date toc would use config option with default \n. Can Result in mixed doc as per now if not configured otherwise.
- \r\n docs already with toc containing normalised line endings via script would use \r\n, changed behaviour. This would be low likelihood but what user wants as it removes need to add in a normalisation process. Effectively a bug fix.
- \r\n doc without toc would use \r\n, changed behaviour. In this case it is a change but avoids creating a mixed document which I see as a positive.
- \n doc without toc would use \n, no changed behaviour.


So we would only get a chance in a few scenarios. Let me know if you are on the same page.

File: lib/transform.js (hunk 3 above)
Comment (thompson-tomo) [reply lib/transform.js]: I agree, byte by byte would be more efficient.

File: lib/transform.js (hunk 2 above)
Comment (thompson-tomo) [reply lib/transform.js]: Thinking about this some more, I feel we can merge this without the configurable default. That way this can be released as part of 2.4.1 due to it purely being a fix. This is because the only time a user would see a change is if they are post processing the toc to normalize the endings and all they would see is their processing would have no effect and for new docs we are avoiding introducing a line ending mismatch.

File: lib/transform.js (hunk 1 above)
Comment (thompson-tomo) [reply lib/transform.js]: Let's push configurable option to next minor.

**Comment by thompson-tomo** [comment]
@AndrewSouthpaw now that #338 is merged this one is good for review.

**Review by AndrewSouthpaw — APPROVED** [review]
